[build]
  # Comando de build
  command = "npm run build"
  # Directorio donde se generan los archivos estáticos
  publish = "dist"

# Configuración para SPAs (Single Page Applications)
# Redirige todas las rutas al index.html para que React Router funcione
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad y cache
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache para assets estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache para service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"